server
{
    listen 80;
    server_name suseong.org www.suseong.org;
    return 301 https://$host$request_uri;
}

server
{
    listen 443 ssl;
    server_name suseong.org www.suseong.org;

    ssl_certificate /etc/nginx/certs/suseong.org.crt;
    ssl_certificate_key /etc/nginx/certs/suseong.org.key;

    root /usr/share/nginx/html;
    index index.html;

    location /api/
    {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /
    {
        try_files $uri $uri/ =404;
    }
}
